---
- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Check status of selinux
  shell: getenforce

- name: Permissive selinux
  selinux: policy=targeted state=permissive

- name: test connection (before reboot)
  ping:

- name: reboot!
  command: shutdown -r now

- name: wait for SSH port down
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped

- name: wait for SSH port up
  wait_for: host={{ inventory_hostname }} port=22 state=started delay=30
  delegate_to: 127.0.0.1

- name: test connection (after reboot)
  ping:
